// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/category_statistic.dart';
import 'models/free_time_slot.dart';
import 'models/playlist.dart';
import 'models/reminder.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8391305720767107248),
    name: 'FreeTimeSlot',
    lastPropertyId: const obx_int.IdUid(4, 8229507221035340727),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6976839060275640967),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8011756357796347632),
        name: 'dayOfWeek',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 91074731690441541),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8229507221035340727),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2467552958308754850),
    name: 'Reminder',
    lastPropertyId: const obx_int.IdUid(34, 4297586429664833521),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5065033350240028397),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5533952059487614277),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8333439630692358589),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3102023776887761994),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3690836291949707873),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 564003022156517493),
        name: 'importance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5898340908090500740),
        name: 'scheduledAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6893949958700736561),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4383945327753081948),
        name: 'isOpened',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5584951653186768395),
        name: 'openedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8748440234240307710),
        name: 'aiExplanation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2002966607196827423),
        name: 'categoryEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5374404121842304787),
        name: 'categoryAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4900016881022313226),
        name: 'complexityEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3957910534601843264),
        name: 'complexityAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8428746412670309728),
        name: 'isEthical',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5688975550288732113),
        name: 'ethicalReasoning',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5190634068976515636),
        name: 'categoryFr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1918227050185131452),
        name: 'complexityFr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5109539699443776352),
        name: 'ethicalReasoningAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 7180512601247276094),
        name: 'ethicalReasoningFr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 8597590637455557837),
        name: 'aiExplanationAr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 6645167268792357502),
        name: 'aiExplanationFr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 2483828379425149794),
        name: 'isPlaylist',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 112333797488466323),
        name: 'playlistId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 3424527295164801761),
        name: 'playlistCurrentIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 3187343118136554315),
        name: 'playlistTotalItems',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 3133621524900684366),
        name: 'currentVideoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 7880347285899066685),
        name: 'playlistTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 7074773747689110051),
        name: 'playlistThumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 7429483713193910613),
        name: 'rescheduleAttempts',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5558201076700029749),
    name: 'CategoryStatistic',
    lastPropertyId: const obx_int.IdUid(12, 476757389788043514),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2775659467839446326),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1076798253833412995),
        name: 'categoryEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3753862427159586139),
        name: 'complexityEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1629367029688522289),
        name: 'totalCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 960385327034205957),
        name: 'openedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5703710819172563485),
        name: 'notOpenedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4377567802903910931),
        name: 'avgSecondsToOpen',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5414399194519381966),
        name: 'openedHoursJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5510517105731074338),
        name: 'openedDaysJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5299121973323168192),
        name: 'notOpenedHoursJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 637451293399895644),
        name: 'notOpenedDaysJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 476757389788043514),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5088578924645899775),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(12, 726856723989113725),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8964648203298564146),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7451570512512322813),
        name: 'playlistId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6260347334521652879),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5486149699957157233),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3511626142317254856),
        name: 'thumbnailUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8588150688714563662),
        name: 'channelName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 614955385569737598),
        name: 'channelUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 761199055490528021),
        name: 'totalItems',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3298792599994375895),
        name: 'currentIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1274489429418688800),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 489289389215556434),
        name: 'lastAccessedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 726856723989113725),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5088578924645899775),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1339181294488918853,
      4257658286914796969,
      4297586429664833521,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FreeTimeSlot: obx_int.EntityDefinition<FreeTimeSlot>(
      model: _entities[0],
      toOneRelations: (FreeTimeSlot object) => [],
      toManyRelations: (FreeTimeSlot object) => {},
      getId: (FreeTimeSlot object) => object.id,
      setId: (FreeTimeSlot object, int id) {
        object.id = id;
      },
      objectToFB: (FreeTimeSlot object, fb.Builder fbb) {
        final startTimeOffset = fbb.writeString(object.startTime);
        final endTimeOffset = fbb.writeString(object.endTime);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.dayOfWeek);
        fbb.addOffset(2, startTimeOffset);
        fbb.addOffset(3, endTimeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dayOfWeekParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = FreeTimeSlot(
          id: idParam,
          dayOfWeek: dayOfWeekParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
        );

        return object;
      },
    ),
    Reminder: obx_int.EntityDefinition<Reminder>(
      model: _entities[1],
      toOneRelations: (Reminder object) => [],
      toManyRelations: (Reminder object) => {},
      getId: (Reminder object) => object.id,
      setId: (Reminder object, int id) {
        object.id = id;
      },
      objectToFB: (Reminder object, fb.Builder fbb) {
        final urlOffset = fbb.writeString(object.url);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final importanceOffset = fbb.writeString(object.importance);
        final aiExplanationOffset = object.aiExplanation == null
            ? null
            : fbb.writeString(object.aiExplanation!);
        final categoryEnOffset = object.categoryEn == null
            ? null
            : fbb.writeString(object.categoryEn!);
        final categoryArOffset = object.categoryAr == null
            ? null
            : fbb.writeString(object.categoryAr!);
        final complexityEnOffset = object.complexityEn == null
            ? null
            : fbb.writeString(object.complexityEn!);
        final complexityArOffset = object.complexityAr == null
            ? null
            : fbb.writeString(object.complexityAr!);
        final ethicalReasoningOffset = object.ethicalReasoning == null
            ? null
            : fbb.writeString(object.ethicalReasoning!);
        final categoryFrOffset = object.categoryFr == null
            ? null
            : fbb.writeString(object.categoryFr!);
        final complexityFrOffset = object.complexityFr == null
            ? null
            : fbb.writeString(object.complexityFr!);
        final ethicalReasoningArOffset = object.ethicalReasoningAr == null
            ? null
            : fbb.writeString(object.ethicalReasoningAr!);
        final ethicalReasoningFrOffset = object.ethicalReasoningFr == null
            ? null
            : fbb.writeString(object.ethicalReasoningFr!);
        final aiExplanationArOffset = object.aiExplanationAr == null
            ? null
            : fbb.writeString(object.aiExplanationAr!);
        final aiExplanationFrOffset = object.aiExplanationFr == null
            ? null
            : fbb.writeString(object.aiExplanationFr!);
        final playlistIdOffset = object.playlistId == null
            ? null
            : fbb.writeString(object.playlistId!);
        final currentVideoUrlOffset = object.currentVideoUrl == null
            ? null
            : fbb.writeString(object.currentVideoUrl!);
        final playlistTitleOffset = object.playlistTitle == null
            ? null
            : fbb.writeString(object.playlistTitle!);
        final playlistThumbnailOffset = object.playlistThumbnail == null
            ? null
            : fbb.writeString(object.playlistThumbnail!);
        fbb.startTable(35);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, urlOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, imageUrlOffset);
        fbb.addOffset(7, importanceOffset);
        fbb.addInt64(8, object.scheduledAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(10, object.isOpened);
        fbb.addInt64(11, object.openedAt?.millisecondsSinceEpoch);
        fbb.addOffset(12, aiExplanationOffset);
        fbb.addOffset(13, categoryEnOffset);
        fbb.addOffset(14, categoryArOffset);
        fbb.addOffset(15, complexityEnOffset);
        fbb.addOffset(16, complexityArOffset);
        fbb.addBool(17, object.isEthical);
        fbb.addOffset(18, ethicalReasoningOffset);
        fbb.addOffset(19, categoryFrOffset);
        fbb.addOffset(20, complexityFrOffset);
        fbb.addOffset(21, ethicalReasoningArOffset);
        fbb.addOffset(22, ethicalReasoningFrOffset);
        fbb.addOffset(23, aiExplanationArOffset);
        fbb.addOffset(24, aiExplanationFrOffset);
        fbb.addBool(25, object.isPlaylist);
        fbb.addOffset(26, playlistIdOffset);
        fbb.addInt64(27, object.playlistCurrentIndex);
        fbb.addInt64(28, object.playlistTotalItems);
        fbb.addOffset(29, currentVideoUrlOffset);
        fbb.addOffset(30, playlistTitleOffset);
        fbb.addOffset(31, playlistThumbnailOffset);
        fbb.addInt64(32, object.rescheduleAttempts);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final openedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final categoryEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final categoryArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final categoryFrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final complexityEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final complexityArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final complexityFrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final isEthicalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final ethicalReasoningParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final ethicalReasoningArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final ethicalReasoningFrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final importanceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final scheduledAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final openedAtParam = openedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(openedAtValue);
        final isOpenedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final aiExplanationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final aiExplanationArParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final aiExplanationFrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final rescheduleAttemptsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          68,
          0,
        );
        final object =
            Reminder(
                id: idParam,
                url: urlParam,
                title: titleParam,
                description: descriptionParam,
                imageUrl: imageUrlParam,
                categoryEn: categoryEnParam,
                categoryAr: categoryArParam,
                categoryFr: categoryFrParam,
                complexityEn: complexityEnParam,
                complexityAr: complexityArParam,
                complexityFr: complexityFrParam,
                isEthical: isEthicalParam,
                ethicalReasoning: ethicalReasoningParam,
                ethicalReasoningAr: ethicalReasoningArParam,
                ethicalReasoningFr: ethicalReasoningFrParam,
                importance: importanceParam,
                scheduledAt: scheduledAtParam,
                createdAt: createdAtParam,
                openedAt: openedAtParam,
                isOpened: isOpenedParam,
                aiExplanation: aiExplanationParam,
                aiExplanationAr: aiExplanationArParam,
                aiExplanationFr: aiExplanationFrParam,
                rescheduleAttempts: rescheduleAttemptsParam,
              )
              ..isPlaylist = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                54,
                false,
              )
              ..playlistId = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 56)
              ..playlistCurrentIndex = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                58,
              )
              ..playlistTotalItems = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                60,
              )
              ..currentVideoUrl = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 62)
              ..playlistTitle = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 64)
              ..playlistThumbnail = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 66);

        return object;
      },
    ),
    CategoryStatistic: obx_int.EntityDefinition<CategoryStatistic>(
      model: _entities[2],
      toOneRelations: (CategoryStatistic object) => [],
      toManyRelations: (CategoryStatistic object) => {},
      getId: (CategoryStatistic object) => object.id,
      setId: (CategoryStatistic object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryStatistic object, fb.Builder fbb) {
        final categoryEnOffset = fbb.writeString(object.categoryEn);
        final complexityEnOffset = fbb.writeString(object.complexityEn);
        final openedHoursJsonOffset = object.openedHoursJson == null
            ? null
            : fbb.writeString(object.openedHoursJson!);
        final openedDaysJsonOffset = object.openedDaysJson == null
            ? null
            : fbb.writeString(object.openedDaysJson!);
        final notOpenedHoursJsonOffset = object.notOpenedHoursJson == null
            ? null
            : fbb.writeString(object.notOpenedHoursJson!);
        final notOpenedDaysJsonOffset = object.notOpenedDaysJson == null
            ? null
            : fbb.writeString(object.notOpenedDaysJson!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categoryEnOffset);
        fbb.addOffset(2, complexityEnOffset);
        fbb.addInt64(3, object.totalCount);
        fbb.addInt64(4, object.openedCount);
        fbb.addInt64(5, object.notOpenedCount);
        fbb.addFloat64(6, object.avgSecondsToOpen);
        fbb.addOffset(7, openedHoursJsonOffset);
        fbb.addOffset(8, openedDaysJsonOffset);
        fbb.addOffset(9, notOpenedHoursJsonOffset);
        fbb.addOffset(10, notOpenedDaysJsonOffset);
        fbb.addInt64(11, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final complexityEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final totalCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final openedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final notOpenedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final avgSecondsToOpenParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final openedHoursJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final openedDaysJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final notOpenedHoursJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final notOpenedDaysJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final object = CategoryStatistic(
          id: idParam,
          categoryEn: categoryEnParam,
          complexityEn: complexityEnParam,
          totalCount: totalCountParam,
          openedCount: openedCountParam,
          notOpenedCount: notOpenedCountParam,
          avgSecondsToOpen: avgSecondsToOpenParam,
          openedHoursJson: openedHoursJsonParam,
          openedDaysJson: openedDaysJsonParam,
          notOpenedHoursJson: notOpenedHoursJsonParam,
          notOpenedDaysJson: notOpenedDaysJsonParam,
          lastUpdated: lastUpdatedParam,
        );

        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[3],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {},
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final playlistIdOffset = fbb.writeString(object.playlistId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final thumbnailUrlOffset = object.thumbnailUrl == null
            ? null
            : fbb.writeString(object.thumbnailUrl!);
        final channelNameOffset = fbb.writeString(object.channelName);
        final channelUrlOffset = fbb.writeString(object.channelUrl);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, playlistIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, thumbnailUrlOffset);
        fbb.addOffset(5, channelNameOffset);
        fbb.addOffset(6, channelUrlOffset);
        fbb.addInt64(7, object.totalItems);
        fbb.addInt64(8, object.currentIndex);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.lastAccessedAt.millisecondsSinceEpoch);
        fbb.addBool(11, object.isCompleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playlistIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final thumbnailUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final channelNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final channelUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final totalItemsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final currentIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final lastAccessedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final object = Playlist(
          id: idParam,
          playlistId: playlistIdParam,
          title: titleParam,
          description: descriptionParam,
          thumbnailUrl: thumbnailUrlParam,
          channelName: channelNameParam,
          channelUrl: channelUrlParam,
          totalItems: totalItemsParam,
          currentIndex: currentIndexParam,
          createdAt: createdAtParam,
          lastAccessedAt: lastAccessedAtParam,
          isCompleted: isCompletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FreeTimeSlot] entity fields to define ObjectBox queries.
class FreeTimeSlot_ {
  /// See [FreeTimeSlot.id].
  static final id = obx.QueryIntegerProperty<FreeTimeSlot>(
    _entities[0].properties[0],
  );

  /// See [FreeTimeSlot.dayOfWeek].
  static final dayOfWeek = obx.QueryIntegerProperty<FreeTimeSlot>(
    _entities[0].properties[1],
  );

  /// See [FreeTimeSlot.startTime].
  static final startTime = obx.QueryStringProperty<FreeTimeSlot>(
    _entities[0].properties[2],
  );

  /// See [FreeTimeSlot.endTime].
  static final endTime = obx.QueryStringProperty<FreeTimeSlot>(
    _entities[0].properties[3],
  );
}

/// [Reminder] entity fields to define ObjectBox queries.
class Reminder_ {
  /// See [Reminder.id].
  static final id = obx.QueryIntegerProperty<Reminder>(
    _entities[1].properties[0],
  );

  /// See [Reminder.url].
  static final url = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[1],
  );

  /// See [Reminder.title].
  static final title = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[2],
  );

  /// See [Reminder.description].
  static final description = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[3],
  );

  /// See [Reminder.imageUrl].
  static final imageUrl = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[4],
  );

  /// See [Reminder.importance].
  static final importance = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[5],
  );

  /// See [Reminder.scheduledAt].
  static final scheduledAt = obx.QueryDateProperty<Reminder>(
    _entities[1].properties[6],
  );

  /// See [Reminder.createdAt].
  static final createdAt = obx.QueryDateProperty<Reminder>(
    _entities[1].properties[7],
  );

  /// See [Reminder.isOpened].
  static final isOpened = obx.QueryBooleanProperty<Reminder>(
    _entities[1].properties[8],
  );

  /// See [Reminder.openedAt].
  static final openedAt = obx.QueryDateProperty<Reminder>(
    _entities[1].properties[9],
  );

  /// See [Reminder.aiExplanation].
  static final aiExplanation = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[10],
  );

  /// See [Reminder.categoryEn].
  static final categoryEn = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[11],
  );

  /// See [Reminder.categoryAr].
  static final categoryAr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[12],
  );

  /// See [Reminder.complexityEn].
  static final complexityEn = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[13],
  );

  /// See [Reminder.complexityAr].
  static final complexityAr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[14],
  );

  /// See [Reminder.isEthical].
  static final isEthical = obx.QueryBooleanProperty<Reminder>(
    _entities[1].properties[15],
  );

  /// See [Reminder.ethicalReasoning].
  static final ethicalReasoning = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[16],
  );

  /// See [Reminder.categoryFr].
  static final categoryFr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[17],
  );

  /// See [Reminder.complexityFr].
  static final complexityFr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[18],
  );

  /// See [Reminder.ethicalReasoningAr].
  static final ethicalReasoningAr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[19],
  );

  /// See [Reminder.ethicalReasoningFr].
  static final ethicalReasoningFr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[20],
  );

  /// See [Reminder.aiExplanationAr].
  static final aiExplanationAr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[21],
  );

  /// See [Reminder.aiExplanationFr].
  static final aiExplanationFr = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[22],
  );

  /// See [Reminder.isPlaylist].
  static final isPlaylist = obx.QueryBooleanProperty<Reminder>(
    _entities[1].properties[23],
  );

  /// See [Reminder.playlistId].
  static final playlistId = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[24],
  );

  /// See [Reminder.playlistCurrentIndex].
  static final playlistCurrentIndex = obx.QueryIntegerProperty<Reminder>(
    _entities[1].properties[25],
  );

  /// See [Reminder.playlistTotalItems].
  static final playlistTotalItems = obx.QueryIntegerProperty<Reminder>(
    _entities[1].properties[26],
  );

  /// See [Reminder.currentVideoUrl].
  static final currentVideoUrl = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[27],
  );

  /// See [Reminder.playlistTitle].
  static final playlistTitle = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[28],
  );

  /// See [Reminder.playlistThumbnail].
  static final playlistThumbnail = obx.QueryStringProperty<Reminder>(
    _entities[1].properties[29],
  );

  /// See [Reminder.rescheduleAttempts].
  static final rescheduleAttempts = obx.QueryIntegerProperty<Reminder>(
    _entities[1].properties[30],
  );
}

/// [CategoryStatistic] entity fields to define ObjectBox queries.
class CategoryStatistic_ {
  /// See [CategoryStatistic.id].
  static final id = obx.QueryIntegerProperty<CategoryStatistic>(
    _entities[2].properties[0],
  );

  /// See [CategoryStatistic.categoryEn].
  static final categoryEn = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[1],
  );

  /// See [CategoryStatistic.complexityEn].
  static final complexityEn = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[2],
  );

  /// See [CategoryStatistic.totalCount].
  static final totalCount = obx.QueryIntegerProperty<CategoryStatistic>(
    _entities[2].properties[3],
  );

  /// See [CategoryStatistic.openedCount].
  static final openedCount = obx.QueryIntegerProperty<CategoryStatistic>(
    _entities[2].properties[4],
  );

  /// See [CategoryStatistic.notOpenedCount].
  static final notOpenedCount = obx.QueryIntegerProperty<CategoryStatistic>(
    _entities[2].properties[5],
  );

  /// See [CategoryStatistic.avgSecondsToOpen].
  static final avgSecondsToOpen = obx.QueryDoubleProperty<CategoryStatistic>(
    _entities[2].properties[6],
  );

  /// See [CategoryStatistic.openedHoursJson].
  static final openedHoursJson = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[7],
  );

  /// See [CategoryStatistic.openedDaysJson].
  static final openedDaysJson = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[8],
  );

  /// See [CategoryStatistic.notOpenedHoursJson].
  static final notOpenedHoursJson = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[9],
  );

  /// See [CategoryStatistic.notOpenedDaysJson].
  static final notOpenedDaysJson = obx.QueryStringProperty<CategoryStatistic>(
    _entities[2].properties[10],
  );

  /// See [CategoryStatistic.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<CategoryStatistic>(
    _entities[2].properties[11],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[3].properties[0],
  );

  /// See [Playlist.playlistId].
  static final playlistId = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[1],
  );

  /// See [Playlist.title].
  static final title = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[2],
  );

  /// See [Playlist.description].
  static final description = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[3],
  );

  /// See [Playlist.thumbnailUrl].
  static final thumbnailUrl = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[4],
  );

  /// See [Playlist.channelName].
  static final channelName = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[5],
  );

  /// See [Playlist.channelUrl].
  static final channelUrl = obx.QueryStringProperty<Playlist>(
    _entities[3].properties[6],
  );

  /// See [Playlist.totalItems].
  static final totalItems = obx.QueryIntegerProperty<Playlist>(
    _entities[3].properties[7],
  );

  /// See [Playlist.currentIndex].
  static final currentIndex = obx.QueryIntegerProperty<Playlist>(
    _entities[3].properties[8],
  );

  /// See [Playlist.createdAt].
  static final createdAt = obx.QueryDateProperty<Playlist>(
    _entities[3].properties[9],
  );

  /// See [Playlist.lastAccessedAt].
  static final lastAccessedAt = obx.QueryDateProperty<Playlist>(
    _entities[3].properties[10],
  );

  /// See [Playlist.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Playlist>(
    _entities[3].properties[11],
  );
}
